# Created by: Nikos Ntarmos <ntarmos@ceid.upatras.gr>
# $FreeBSD: head/devel/libconfig/Makefile 434587 2017-02-22 15:02:18Z bapt $

PORTNAME=	libconfig
PORTVERSION=	1.7.2
CATEGORIES=	devel
# MASTER_SITES=	http://www.hyperrealm.com/libconfig/

MAINTAINER=	ntarmos@ceid.upatras.gr
COMMENT=	Simple library for manipulating structured configuration files

LICENSE=	LGPL21

CONFLICTS=	wand-libconfig-[0-9]*

USES=	cmake

USE_GITHUB=	YES
GH_ACCOUNT=	hyperrealm
GH_PROJECT=	libconfig
GH_TAGNAME=	9716f62

.include <bsd.port.mk>
