# $FreeBSD$

PORTNAME=	pkginfo
PORTVERSION=	1.2.1
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	che@bein.link
COMMENT=	Query metadatdata from sdists / bdists / installed packages.

LICENSE=	MIT

#RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}click>=3.2:${PORTSDIR}/devel/py-click \

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
