# $FreeBSD$

PORTNAME=	flask-bootstrap
PORTVERSION=	3.3.2.1
CATEGORIES=	python www
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Flask-Bootstrap-${PORTVERSION}

MAINTAINER=	che@bein.link
COMMENT=	Flask extension that includes Bootstrap into your project

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}Flask>=0.10.1:${PORTSDIR}/www/py-flask

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
