# $FreeBSD$

PORTNAME=		fire
PORTVERSION=	0.1.1
CATEGORIES=		devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=		che@bein.link
COMMENT=		Library for automatically generating command line interfaces

LICENSE=		APACHE2
# LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=			python
USE_PYTHON=		autoplist distutils

.include <bsd.port.mk>
