# $FreeBSD$

PORTNAME=		sh
PORTVERSION=	1.11
CATEGORIES=		devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=		che@bein.link
COMMENT=		Python subprocess interface

LICENSE=		MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USE_GITHUB=		yes
GH_ACCOUNT=		amoffat
GH_COMMIT=		c361f94

USES=			python
USE_PYTHON=		autoplist distutils

.include <bsd.port.mk>
