# $FreeBSD$

PORTNAME=	Flask-Disqus
PORTVERSION=	0.0.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	che@bein.link
COMMENT=	Flask extension that includes Disqus comments into your project

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}Flask>=0.10.1:www/py-flask

USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
