# $FreeBSD$

PORTNAME=	Kallithea
PORTVERSION=	0.2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	che@bein.link
COMMENT=	Python Owncloud client library

LICENSE=	Apache
LICENSE_FILE=	${WRKSRC}/Apache-License-2.0.txt


USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
