# $FreeBSD$

PORTNAME=	pytractor
PORTVERSION=	0.2.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	che@bein.link
COMMENT=	Python Git Library

LICENSE=	APACHE20

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}future>=0.15.2:devel/py-future \
	${PYTHON_PKGNAMEPREFIX}selenium>=2.43.0:www/py-selenium

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
